ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: traefik
    hosts:
      - app.kbnhvn-project.eu
    path: /prometheus
    pathType: Prefix
service:
  enabled: true
  type: ClusterIP
  servicePort: 80