apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pv-claim
  namespace: monitoring
spec:
  storageClassName: efs-sc
  volumeName: efs-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi