region              = "eu-west-3"
vpc_name            = "kbnhvn-vpc"
vpc_cidr            = "10.0.0.0/16"
public_subnets      = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
private_subnets     = ["10.0.4.0/24", "10.0.5.0/24", "10.0.6.0/24"]
availability_zones  = ["eu-west-3a", "eu-west-3b", "eu-west-3c"]
key_name            = "AWS-DST-Infra"
cluster_name        = "kbnhvn-cluster"
domain_name         = "devops.kbnhvn-project.eu"
route53_zone_id     = "Z3P5QSUBK4POTI"
prefix              = "AirQuality"
environment         = "dev"
desired_capacity    = 2
max_capacity        = 3
min_capacity        = 1
instance_type       = "t3.medium"
