apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-db
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: <DATA>
    volumeAttributes:
      mounttargetip: <DNS>
