apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: default
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgres-backup
            image: amazonlinux:2
            env:
            - name: PGUSER
              value: "${PGUSER}"
            - name: PGPASSWORD
              value: "${PGPASSWORD}"
            - name: PGHOST
              value: "${PGHOST}"
            - name: PGDATABASE
              value: "${PGDATABASE}"
            - name: POSTGRES_BUCKET
              value: "${POSTGRES_BUCKET}"
            - name: AWS_ACCESS_KEY_ID
              value: "${AWS_ACCESS_KEY_ID}"
            - name: AWS_SECRET_ACCESS_KEY
              value: "${AWS_SECRET_ACCESS_KEY}"
            volumeMounts:
            - name: backup-scripts
              mountPath: /scripts
            command: ["/bin/bash", "-c", "/scripts/backup_postgres.sh"]
          volumes:
          - name: backup-scripts
            configMap:
              name: backup-scripts
          restartPolicy: OnFailure
