apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: elasticsearch-backup
  namespace: default
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: elasticsearch-backup
            image: amazonlinux:2
            env:
            - name: ES_HOST
              value: "${ES_HOST}"
            - name: ELASTICSEARCH_BUCKET
              value: "${ELASTICSEARCH_BUCKET}"
            - name: AWS_ACCESS_KEY_ID
              value: "${AWS_ACCESS_KEY_ID}"
            - name: AWS_SECRET_ACCESS_KEY
              value: "${AWS_SECRET_ACCESS_KEY}"
            volumeMounts:
            - name: backup-scripts
              mountPath: /scripts
            command: ["/bin/bash", "-c", "/scripts/backup_elasticsearch.sh"]
          volumes:
          - name: backup-scripts
            configMap:
              name: backup-scripts
          restartPolicy: OnFailure
