# jenkins-agent-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-agent-config
  namespace: jenkins
data:
  jenkins-agent.yaml: |
    kind: Pod
    apiVersion: v1
    metadata:
      labels:
        jenkins/label: docker
    spec:
      containers:
      - name: jnlp
        image: jenkins/inbound-agent:alpine
        args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
      - name: docker
        image: docker:19.03
        command:
        - cat
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
