ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: traefik
    hosts:
      - app.kbnhvn-project.eu
    path: /grafana
    pathType: Prefix
service:
  enabled: true
  type: ClusterIP
  port: 80